# Generated by Django 3.1.1 on 2020-09-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
