# Generated by Django 3.1.1 on 2020-09-15 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_records'),
        ('api', '0004_artist_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('records', models.ManyToManyField(to='api.Record')),
            ],
            options={
                'verbose_name_plural': 'collections',
            },
        ),
    ]
