# Generated by Django 3.1.1 on 2020-09-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_artist_record'),
        ('authentication', '0002_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='records',
            field=models.ManyToManyField(to='api.Record'),
        ),
    ]
