# Generated by Django 3.1.1 on 2020-09-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200915_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='records',
        ),
    ]
